/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.amazon.itemservice.dto;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductCategory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5835232606304528593L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductCategory\",\"namespace\":\"schema\",\"fields\":[{\"name\":\"categoryName\",\"type\":\"string\"},{\"name\":\"categoryCode\",\"type\":\"string\"},{\"name\":\"categoryDescription\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProductCategory> ENCODER =
      new BinaryMessageEncoder<ProductCategory>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductCategory> DECODER =
      new BinaryMessageDecoder<ProductCategory>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductCategory> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductCategory> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductCategory> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ProductCategory>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductCategory to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductCategory from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductCategory instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductCategory fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence categoryName;
   private java.lang.CharSequence categoryCode;
   private java.lang.CharSequence categoryDescription;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductCategory() {}

  /**
   * All-args constructor.
   * @param categoryName The new value for categoryName
   * @param categoryCode The new value for categoryCode
   * @param categoryDescription The new value for categoryDescription
   */
  public ProductCategory(java.lang.CharSequence categoryName, java.lang.CharSequence categoryCode, java.lang.CharSequence categoryDescription) {
    this.categoryName = categoryName;
    this.categoryCode = categoryCode;
    this.categoryDescription = categoryDescription;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return categoryName;
    case 1: return categoryCode;
    case 2: return categoryDescription;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: categoryName = (java.lang.CharSequence)value$; break;
    case 1: categoryCode = (java.lang.CharSequence)value$; break;
    case 2: categoryDescription = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'categoryName' field.
   * @return The value of the 'categoryName' field.
   */
  public java.lang.CharSequence getCategoryName() {
    return categoryName;
  }


  /**
   * Sets the value of the 'categoryName' field.
   * @param value the value to set.
   */
  public void setCategoryName(java.lang.CharSequence value) {
    this.categoryName = value;
  }

  /**
   * Gets the value of the 'categoryCode' field.
   * @return The value of the 'categoryCode' field.
   */
  public java.lang.CharSequence getCategoryCode() {
    return categoryCode;
  }


  /**
   * Sets the value of the 'categoryCode' field.
   * @param value the value to set.
   */
  public void setCategoryCode(java.lang.CharSequence value) {
    this.categoryCode = value;
  }

  /**
   * Gets the value of the 'categoryDescription' field.
   * @return The value of the 'categoryDescription' field.
   */
  public java.lang.CharSequence getCategoryDescription() {
    return categoryDescription;
  }


  /**
   * Sets the value of the 'categoryDescription' field.
   * @param value the value to set.
   */
  public void setCategoryDescription(java.lang.CharSequence value) {
    this.categoryDescription = value;
  }

  /**
   * Creates a new ProductCategory RecordBuilder.
   * @return A new ProductCategory RecordBuilder
   */
  public static ProductCategory.Builder newBuilder() {
    return new ProductCategory.Builder();
  }

  /**
   * Creates a new ProductCategory RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductCategory RecordBuilder
   */
  public static ProductCategory.Builder newBuilder(ProductCategory.Builder other) {
    if (other == null) {
      return new ProductCategory.Builder();
    } else {
      return new ProductCategory.Builder(other);
    }
  }

  /**
   * Creates a new ProductCategory RecordBuilder by copying an existing ProductCategory instance.
   * @param other The existing instance to copy.
   * @return A new ProductCategory RecordBuilder
   */
  public static ProductCategory.Builder newBuilder(ProductCategory other) {
    if (other == null) {
      return new ProductCategory.Builder();
    } else {
      return new ProductCategory.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductCategory instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductCategory>
    implements org.apache.avro.data.RecordBuilder<ProductCategory> {

    private java.lang.CharSequence categoryName;
    private java.lang.CharSequence categoryCode;
    private java.lang.CharSequence categoryDescription;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ProductCategory.Builder other) {
      super(other);
      if (RecordBuilderBase.isValidValue(fields()[0], other.categoryName)) {
        this.categoryName = data().deepCopy(fields()[0].schema(), other.categoryName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (RecordBuilderBase.isValidValue(fields()[1], other.categoryCode)) {
        this.categoryCode = data().deepCopy(fields()[1].schema(), other.categoryCode);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (RecordBuilderBase.isValidValue(fields()[2], other.categoryDescription)) {
        this.categoryDescription = data().deepCopy(fields()[2].schema(), other.categoryDescription);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductCategory instance
     * @param other The existing instance to copy.
     */
    private Builder(ProductCategory other) {
      super(SCHEMA$);
      if (RecordBuilderBase.isValidValue(fields()[0], other.categoryName)) {
        this.categoryName = data().deepCopy(fields()[0].schema(), other.categoryName);
        fieldSetFlags()[0] = true;
      }
      if (RecordBuilderBase.isValidValue(fields()[1], other.categoryCode)) {
        this.categoryCode = data().deepCopy(fields()[1].schema(), other.categoryCode);
        fieldSetFlags()[1] = true;
      }
      if (RecordBuilderBase.isValidValue(fields()[2], other.categoryDescription)) {
        this.categoryDescription = data().deepCopy(fields()[2].schema(), other.categoryDescription);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'categoryName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCategoryName() {
      return categoryName;
    }


    /**
      * Sets the value of the 'categoryName' field.
      * @param value The value of 'categoryName'.
      * @return This builder.
      */
    public ProductCategory.Builder setCategoryName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.categoryName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'categoryName' field has been set.
      * @return True if the 'categoryName' field has been set, false otherwise.
      */
    public boolean hasCategoryName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'categoryName' field.
      * @return This builder.
      */
    public ProductCategory.Builder clearCategoryName() {
      categoryName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'categoryCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getCategoryCode() {
      return categoryCode;
    }


    /**
      * Sets the value of the 'categoryCode' field.
      * @param value The value of 'categoryCode'.
      * @return This builder.
      */
    public ProductCategory.Builder setCategoryCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.categoryCode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'categoryCode' field has been set.
      * @return True if the 'categoryCode' field has been set, false otherwise.
      */
    public boolean hasCategoryCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'categoryCode' field.
      * @return This builder.
      */
    public ProductCategory.Builder clearCategoryCode() {
      categoryCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'categoryDescription' field.
      * @return The value.
      */
    public java.lang.CharSequence getCategoryDescription() {
      return categoryDescription;
    }


    /**
      * Sets the value of the 'categoryDescription' field.
      * @param value The value of 'categoryDescription'.
      * @return This builder.
      */
    public ProductCategory.Builder setCategoryDescription(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.categoryDescription = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'categoryDescription' field has been set.
      * @return True if the 'categoryDescription' field has been set, false otherwise.
      */
    public boolean hasCategoryDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'categoryDescription' field.
      * @return This builder.
      */
    public ProductCategory.Builder clearCategoryDescription() {
      categoryDescription = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductCategory build() {
      try {
        ProductCategory record = new ProductCategory();
        record.categoryName = fieldSetFlags()[0] ? this.categoryName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.categoryCode = fieldSetFlags()[1] ? this.categoryCode : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.categoryDescription = fieldSetFlags()[2] ? this.categoryDescription : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductCategory>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductCategory>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductCategory>
    READER$ = (org.apache.avro.io.DatumReader<ProductCategory>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.categoryName);

    out.writeString(this.categoryCode);

    out.writeString(this.categoryDescription);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.categoryName = in.readString(this.categoryName instanceof Utf8 ? (Utf8)this.categoryName : null);

      this.categoryCode = in.readString(this.categoryCode instanceof Utf8 ? (Utf8)this.categoryCode : null);

      this.categoryDescription = in.readString(this.categoryDescription instanceof Utf8 ? (Utf8)this.categoryDescription : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.categoryName = in.readString(this.categoryName instanceof Utf8 ? (Utf8)this.categoryName : null);
          break;

        case 1:
          this.categoryCode = in.readString(this.categoryCode instanceof Utf8 ? (Utf8)this.categoryCode : null);
          break;

        case 2:
          this.categoryDescription = in.readString(this.categoryDescription instanceof Utf8 ? (Utf8)this.categoryDescription : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










