/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.amazon.itemservice.dto;
@org.apache.avro.specific.AvroGenerated
public enum ProductType implements org.apache.avro.generic.GenericEnumSymbol<ProductType> {
  NEW, EXISTING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductType\",\"namespace\":\"schema\",\"symbols\":[\"NEW\",\"EXISTING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
